version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    environment:
      - TZ=UTC

  worker:
    build: .
    depends_on:
      - redis
    command: rq worker --url redis://rq_redis:6379 -c config flight_queue
    environment:
      - TZ=UTC
    volumes:
      - type: bind
        source: ./data
        target: /data

  redis:
    container_name: rq_redis
    image: redis:latest
    ports:
      - "6379:6379"
